[tool.poetry]
name = "relycomply_client"
version = "0.6.0"
description = "A python client for the RelyComply platform"
authors = ["James Saunders <james@relycomply.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<4"
requests = "*"
pandas = "*"
gql = "3.0.0a1"
boto3 = "*"
requests-toolbelt = "*"
littleutils = "*"
toml = "^0.10.2"
Pygments = "^2.10.0"
tabulate = "^0.8.9"
termcolor = "^1.1.0"
PyYAML = "^6.0"
pyarrow = "^6.0.1"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
dephell = "*"
sh = "*"
GitPython = "*"

[tool.dephell.main]
from = { format = "poetry", path = "pyproject.toml" }
to = { format = "setuppy", path = "setup.py" }

[tool.poetry.scripts]
rely = 'relycomply_client.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
