[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]

[tool.poetry]
authors = ["tc-imba <liuyh970615@gmail.com>"]
description = ""
license = "MIT"
name = "pydantic-universal-settings"
version = "0.1.1"

[tool.poetry.dependencies]
click-option-group = "^0.5.3"
psutil = "^5.8.0"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
python = "^3.6.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.14.0"
python-semantic-release = "^7.19.1"

[tool.semantic_release]
branch = "master"
build_command = "poetry build"
upload_to_pypi = true
upload_to_release = true
version_toml = ["pyproject.toml:tool.poetry.version"]
version_variable = ["pydantic_universal_settings/__init__.py:__version__"]
